server:
  port: 8000

spring:
  application:
    name: customer
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/logout
      - /minio/upload
      - /error
      - /user/login
      - /hello
      - /gs-guide-websocket/**